version: '3.8'

services:
  node_backend:
    container_name: node_crud
    image: node_crud:0.0.2
    build:
      context: .
    ports:
      - '3001:3001'
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=crud_db
      - PGUSER=yuri
      - PGPASSWORD=12345
      - PGHOST=node_db
    depends_on:
      - node_db
  node_db:
    container_name: node_db
    image: 'postgres:12'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=yuri
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=crud_db
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}
